### ISSUE TITLE
Add ability to use capturing group from regex in actions

### ISSUE THREAD

**Issue by JordanSussman** [target/flottbot#10]
Currently, regex is fairly simple.. you can just look for patterns and take action on it. it would be nice to be able to use capturing groups and assign to variables to use throughout actions, etc.

simple example:

```yaml
respond: /unlock\s[\<'"]?(.*)[\>'"]?/
args:
  - user
```

If someone typed `unlock <name>`, `name` would be assigned to `user` or `${user}`
