### ISSUE TITLE
Substitute more variables

### ISSUE THREAD

**Issue by sarge** [target/flottbot#101]
I would like to provide environment variables to use in more places.

I would like to have a bot listening in different rooms which are connected to different environments - the utils.Substitute needs to be applied to more variables.

bot.Name - would to have the option to call the my bot(dev) and my bot(prod)
bot.Rooms - I would like to push to differently named rooms

**Comment by JordanSussman** [comment]
@sarge - thanks for opening this, however, I'm not sure I fully understand the use case.

Are you proposing that you have a single bot connected to a single remote (i.e. Slack or Discord), but it is connecting to multiple backends? If so, we typically recommend users create multiple bots to differentiate between the environments. However, we are open to the possibility of making this more flexible. 

Can you post a bit more detailed explanation and/or a sample configuration that achieve the use case?

**Comment by sarge** [comment]
@JordanSussman multiple bots is my use case. To be fair I am still feeling my way through this. I have 3 kubernetes clusters and intend on running one in each cluster. But they will all connect back to a single Slack workspace. I will have 3 different bots configured. What I want to have is commands that call back to a specific room.
```
slack
   operations-ci
   operations-staging
   operations-prod
```
I can have a bot with

```
name: operations
active: true
allow_usergroups:
  - operations
hear: "bots are cool"
reaction: eyes
format_output: "Yeah you ops guys rule too!"
direct_message_only: false
output_to_rooms: 
  - operations-${ENV}

```

Having this parameterised means I can instantiate the same bot for each environment.

Happy to hear your thoughts, or alternative approaches:)

**Comment by JordanSussman** [comment]
Thanks for the clarification! I have a number of quick thoughts on how to solve this:

1. Code modification - Add the [variable](https://target.github.io/flottbot-docs/rules/variables/) of `_bot.name` that maps to the bot `name` defined in the `bot.yml`, and this would allow you to utilize some go templating within the `output_to_rooms` to map the room based on the bot name(s). My thought for that looks like:

```yaml
name: operations
active: true
allow_usergroups:
  - operations
hear: "bots are cool"
reaction: eyes
format_output: "Yeah you ops guys rule too!"
direct_message_only: false
output_to_rooms: |-
  {{ if (eq `${_bot.name}` "operations-dev") }}
  - <custom channel name>
  - ${_bot.name}
  {{ else }}
  - operations-default
  {{ end }}
```

even simpler workflow

```yaml
name: operations
active: true
allow_usergroups:
  - operations
hear: "bots are cool"
reaction: eyes
format_output: "Yeah you ops guys rule too!"
direct_message_only: false
output_to_rooms:
  - ${_bot.name}
```

2. Code modification - Allow you to pass in environment variables to the bot and have the rule(s).yml be rendered with them upon startup (very similar to how we handle the DISCORD_TOKEN and SLACK_TOKEN for the bot.yml today). For example:

```sh
export ENV=dev
```

the rule.yml would render as
```yml
name: operations
active: true
allow_usergroups:
  - operations
hear: "bots are cool"
reaction: eyes
format_output: "Yeah you ops guys rule too!"
direct_message_only: false
output_to_rooms: 
  - operations-dev
```

We would have to add some specific formatting or safeguards to ensure that the interpolation for args doesn't get messed up.

3. Hacky workaround that won't require modifying flottbot - If you are running the bots through docker you could utilize a startup script with [envsubt](https://www.gnu.org/software/gettext/manual/html_node/envsubst-Invocation.html) to render the rule for you this. For example:

    1. Create the `$PWD/config/template` directory
    2. Move the files you want to render from `$PWD/config/rules` to `$PWD/config/template` and ensure they end in `.template`
    3. Create the startup.sh script and modify the permissions

    ```sh
    #!/bin/sh

    mkdir -p /config/rules

    DIRECTORY=/config/templates
    MYVARS='$ENV'
    if [ -d "$DIRECTORY" ];
    then
        for file in /config/templates/*.template
        do
            envsubst "$MYVARS" <"$file" > "/config/rules/$(basename "$file" .template).yml"
        done
    fi

    /flottbot
    ```

    4. Create the Dockerfile and build the image

    ```Dockerfile
    FROM target/flottbot

    RUN apk --update add gettext
    ADD startup.sh /startup.sh

    ENTRYPOINT [ "/startup.sh" ]
    ```

    ```sh
    docker build .
    ```

    5. Run the docker image you created and pass the environment variable

    ```sh

    docker run -e ENV=dev <image id from above>
    ```

Any other thoughts @wass3r @pa3ng?
