### ISSUE TITLE
Dynamically populate help if no help text defined 

### ISSUE THREAD

**Issue by JordanSussman** [target/flottbot#19]
In most cases it's just the match text plus arguments which are available in YAML. We can automatically compose a help message based on that. But we should keep the ability to override for cases where you don't want to show the 'match' value, eg. in cases where it's some crazy regex

For example:
```yaml
respond: hello
args:
  - firstname
  - lastname
```

Based on that we know we can show `hello <firstname> <lastname>`
