### ISSUE TITLE
Bot replies with an ephemeral message to the ignored user/usergroup instead of ignoring them altogether.

### ISSUE THREAD

**Issue by SnehaRaoS26** [target/flottbot#212]
# Report

## What did you do?

ℹ Added a user group to be ignored in "ignore_usergroups" field the YAML  file.

## What did you expect to happen?

ℹ The bot should have ignored the message without giving any kind of reply to the user.

## What happened instead?

ℹ The bot responded with an ephemeral message "You are not allowed to run the 'hello' rule." visible only to the ignored user.

## Screenshots

Internal slack channel so can't share it but consider this:
Me: Hello bot!
(Only visible to you)
bot: You are not allowed to run the 'hello' rule. 

## Your Environment

Please complete the following information):
 - Flottbot version: 0.9.0
 - OS: macOS
 - OS version: 11.6
 - Bot YAML (see below)
 - Rule YAML (see below) if applicable

```yaml
# My .bot.yml file:

name: mybotname
chat_application: slack

slack_token: ${SLACK_TOKEN}
slack_events_callback_path: ${SLACK_EVENTS_CALLBACK_PATH}
slack_signing_secret: ${SLACK_SIGNING_SECRET}

# system
cli: true
# true: enables ability to turn on CLI mode.
# false: disables ability to turn on CLI mode.

```

```yaml
# My rule file:

name: hello
active: true
hear: Hello bot!
ignore_usergroups:
  - some-usergroup
format_output: "Hello!"
start_message_thread: true
direct_message_only: false
```
