### ISSUE TITLE
Rename args prop to expose_args

### ISSUE THREAD

**Issue by JordanSussman** [target/flottbot#24]
```yaml
name: test
match: command
args:
  - var1
```
to
```yaml
name: test
match: command
expose_args:
  - var1
```

This is consistent with `expose_json_fields`. So, any time we expose variable from within rules we would use the `expose_` prefix.
