### ISSUE TITLE
how to call a function with params inside program when a action triggered?a

### ISSUE THREAD

**Issue by lucasjinreal** [target/flottbot#338]
how to call a function with params inside program when a action triggered?a

**Comment by wass3r** [comment]
do you have an example?

you can do:
```yaml
actions:
  - name: sample script
    type: exec
    cmd: python config/scripts/main.py <insert parameter>
```

and your script would handle what to do with the parameter. if you're talking about something else, i might need an example.
