### ISSUE TITLE
output_to_users doesn't work

### ISSUE THREAD

**Issue by wass3r** [target/flottbot#470]
# Report

## What did you do?

used a rule with `output_to_users` containing one list item of a user id

## What did you expect to happen?

the trigger of the rule should have sent a message to that user

## What happened instead?

message wasn't sent

## Your Environment

Please complete the following information):
 - Flottbot version: 0.11+
 - OS: linux
 - OS version: [e.g. 10.13.6]
 - Bot YAML (see below)
 - Rule YAML (see below) if applicable

```yaml
# please paste .bot.yml here (remove any sensitive information!)
```

```yaml
name: msguser
active: true

respond: msguser
args:
  - message

format_output: "${message}"
direct_message_only: false
output_to_users:
  - <userid here>
```
