### ISSUE TITLE
Handle ugly panic stack trace

### ISSUE THREAD

**Issue by pa3ng** [target/flottbot#48]
# Report

## What did you do?

1. Set the metrics field to `false`
2. Build the docker image. Here's my Dockerfile:

```yaml
FROM target/flottbot:golang

ADD config config

CMD ["/go/flottbot"]
```

3. Run the docker image without any environment variables (this will cause the stack trace):

```
docker run -it thorhousebot
```

## What did you expect to happen?

I was expecting a prettier error and more informative error message, i.e. "Your no slack token found" or something like that.

## What happened instead?

Ugly stack trace poop.

## Your Environment

- Run `flottbot --version` and paste the output here: `Version : 0.1.0`
- What OS are you running on? `macOS Sierra version 10.12.6`
- Your `bot.yml` (remove any sensitive information!)
- Maybe the contents of the `.yml` for the rule you're trying to run, if applicable (remove any sensitive information!)

  ```yaml
  # metadata (for logging)
name: thorhousebot # EDIT this (name of bot)

# chat applications
chat_application: slack # EDIT (network to use, e.g. 'slack')
slack_token: ${SLACK_TOKEN} # EDIT ${SLACK_TOKEN}

# system
cli: false # leave this to be 'true' as default
# true: enables ability to turn on CLI mode.
# false: disables ability to turn on CLI mode.

scheduler: false
# true: enables rule scheduling
# false: disables rule scheduling

debug: true
# true: enable logging to console
# false: disable logging

log_json: false
# true: logs will be in JOSN format
# false: logs will be in plain text

# for advanced messaging capabilities
webhook: false # leave this to be 'false' as default

# for prometheus metrics capabilities
metrics: false # 'false': disable prometheus metrics
  ```

  ```yaml
  # please paste contents of your rule, if applicable (remove any sensitive information!)
  ```
