### ISSUE TITLE
Misleading error message on startup

### ISSUE THREAD

**Issue by pa3ng** [target/flottbot#51]
# Report

## What did you do?

Ran the bot normally. Slack token environment variable set.

## What did you expect to happen?

Not see the following in the console log:

```sh
ERRO[0000] Slack Interactive Components callback path is empty:
```

## What happened instead?

I saw the following in the console log:

```sh
ERRO[0000] Slack Interactive Components callback path is empty:
```

## Your Environment

- Run `flottbot --version` and paste the output here: `Version : 0.1.0`
- What OS are you running on? `macOS Sierra version 10.12.6`
- Your `bot.yml` (remove any sensitive information!)
- Maybe the contents of the `.yml` for the rule you're trying to run, if applicable (remove any sensitive information!)

```yaml
  # metadata (for logging)
name: thorhousebot # EDIT this (name of bot)

# chat applications
chat_application: slack # EDIT (network to use, e.g. 'slack')
slack_token: ${SLACK_TOKEN} # EDIT ${SLACK_TOKEN}

# system
cli: false # leave this to be 'true' as default
# true: enables ability to turn on CLI mode.
# false: disables ability to turn on CLI mode.

scheduler: false
# true: enables rule scheduling
# false: disables rule scheduling

debug: true
# true: enable logging to console
# false: disable logging

log_json: false
# true: logs will be in JOSN format
# false: logs will be in plain text

# for advanced messaging capabilities
webhook: false # leave this to be 'false' as default

# for prometheus metrics capabilities
metrics: false # 'false': disable prometheus metrics
```

  ```yaml
  # please paste contents of your rule, if applicable (remove any sensitive information!)
  ```
