### ISSUE TITLE
Provide Hours a bot will be responsive. 

### ISSUE THREAD

**Issue by sjqnn** [target/flottbot#72]
Provide a mechanism that will turn on a chatbot rule on for only a specified period of time. I could see this being implemented in the `rule.yml` like so:

```yaml
# metadata
name: hello
active: true
active_start: 16:00
active_stop: 09:00
```

This would turn the rule active between 4pm-9am for example.

**Comment by jaredanson** [comment]
It would be great if you could also specify day of the week as well. For example having a rule where if someone on the weekend posts something, you could have the bot respond saying contact the on call schedule if this is urgent.

**Comment by sjqnn** [comment]
Maybe we could do something like:

```
name: hello
active: true
  when: [nights, weekends]
```
where nights( 4pm-8am ) and Weekends (Saturday-Sunday) are set by default and determined by the time/date settings on the machine where the bot is hosted? im trying to figure out what would be the most concise way to implement this.

**Comment by jaredanson** [comment]
We have a team in India, so I don't think just defaulting 4pm-8am as off hours would be good for our use case. Our down hours are more like 5pm to 11pm or midnight, so I would like the ability to specify a time range.

I'm not sure concise is necessarily always the best. People might like the ability to set specific days, times, etc. Something like this could work for weekdays:

```
name: weekday-off-hours
active: true
  when: [weekdays]
  timezone: cst
  start: 17:00
  end: 24:00
```
But weekend is slightly more complicated.

```
name: weekend-off-hours
active: true
  timezone: cst
  start:
      day: friday
      time: 17:00
  end:
      day: sunday
      time: 24:00
```
