### ISSUE TITLE
Exec action does not properly handle missing binary

### ISSUE THREAD

**Issue by JordanSussman** [target/flottbot#85]
# Report

## What did you do?

Created a rule with an exec action that had a `cmd` that didn't exist on the system. 

## What did you expect to happen?

Expected error handling to occur

## What happened instead?

The bot outputted `fork/exec ./foo/bar: no such file or directory` directly to Discord.

## Your Environment

Please complete the following information):
 - Flottbot version: master branch
 - OS: macOS

```yaml
# please paste .bot.yml here (remove any sensitive information!)
# chat applications
chat_application: discord

# Discord chat application specific fields.
# required
discord_token: ${DISCORD_TOKEN}

# system
cli: false
# true: enables ability to turn on CLI mode.
# false: disables ability to turn on CLI mode.

scheduler: false
# true: enables rule scheduling
# false: disables rule scheduling

debug: true
# true: enable logging to console
# false: disable logging

log_json: false
# true: logs will be in JSON format
# false: logs will be in plain text

metrics: false
```

```yaml
# meta
name: script-rule
active: true
# trigger and args
respond: script
reaction: "👀"
# actions
actions:
  - name: sample script
    type: exec
    cmd: ./foo/bar
    update_reaction: |-
      {{ if (eq `${_exec_status}` "0") }}
        ✅
      {{ else }}
        ❗
      {{ end }}
# response
format_output: "${_exec_output}"
direct_message_only: false
# help
help_text: script
include_in_help: true
```

## Additional context
Some initial bugging seems to tell me that the error handling struct of the script isn't handling this scenario, so we are falling into the default https://github.com/target/flottbot/blob/42457d3b78a6a04821a6856cd8f0813d6e8ac509/handlers/script.go#L63. Looks like the case statement needs to have `*os.PathError` added to it.
