### ISSUE TITLE
 ignore channel param that can be used while using a rule in multiple channels.

### ISSUE THREAD

**Issue by rajverma1985** [target/flottbot#87]
Not able to ignore a channel while trying to to use the bot rule in multiple channels. if we say allow or ignore then it completely stops working as that person might be a part of multiple rooms. an enhancement for this will be really great.

**Comment by wass3r** [comment]
Just to paraphrase. The bot is present in multiple channels and you have a rule set up that *could* pick up things from any of the channels, but you really only want to apply that rule to one channel?

Assuming the above is accurate, maybe adding a rule-based property named something like `limit_to_channels` that accepts an array of channel names that will be able to process the rule, ie.

```yaml
name: limit-channels-rule
active: true

hear: /help|assist/ 

limit_to_channels:
  - support
  - help
format_output: "how can i help you?"
direct_message_only: false
```
So, even though the bot might be part of `#general` (for example), it will only process messages from the defined channels? Would that work?
