### ISSUE TITLE
Request: Document an acceptible way to launch a container for a command

### ISSUE THREAD

**Issue by pcn** [target/flottbot#88]
From the documentation, I've inferred that the bot container supports an exec of a command in the same container. It would be really useful to document a configuration where a bot would launch a separate container as well.

**Comment by JordanSussman** [comment]
@pcn - you could consider utilizing Docker in Docker (dind) to accomplish this. Note: Mounting in the docker socket has plenty of security concerns, so you should think through the implications of the scripts you allow to be executed and the passed arguments.

For example:

Dockerfile:

```Dockerfile
FROM target/flottbot as base

FROM docker:18.06.3-dind

COPY --from=base /flottbot /flottbot


ENTRYPOINT [ "/flottbot" ]
```

rule.yml

```yml
name: script-rule
active: true
respond: test
actions:
  - name: sample script
    type: exec
    cmd: docker run alpine sh -c "echo foo"
format_output: "${_exec_output}"
direct_message_only: false
```

setup & run commands:

```
docker build -f <path to previously mentioned dockerfile> -t flottbot-docker .
docker run -v $PWD/config:/config -v /var/run/docker.sock:/var/run/docker.sock flottbot-docker
```

Mentioning the above bot with `test` will return `foo`.

Is this the kind of example you were looking for?
