### ISSUE TITLE
Log actions do not work when using "start_message_thread" option

### ISSUE THREAD

**Issue by pa3ng** [target/flottbot#96]
Log action does not send a message to a channel when using `start_message_thread`.

Example rule:
```yaml
...
actions:
  - name: trigger log
    type: log
    message: "Someone used this command"
    limit_to_rooms:
      - flottbot-log
...
start_message_thread: true
```
