### ISSUE TITLE
Embed Welcomebot Functionality

### ISSUE THREAD

**Issue by sjqnn** [target/flottbot#99]
I'm interested in having a bot in my channel 'respond' to when a user enters a channel that it's in.( ie to give community guidelines/ instructions or for onboarding purposes). Something along the lines of this to get a fun cat fact when you first enter the general channel:

```yaml
# meta
name: general_welcome
active: true
welcome_message:
  - channel: general
     enabled: true
# trigger and args
# actions
actions:
  - name: cat facts http request
    type: GET
    url: https://catfact.ninja/fact
    expose_json_fields:
      fact: '.fact'
format_output: "${fact}"
direct_message_only: true
```
